### ISSUE TITLE
Stable Rust: Cannot find the parse_file function

### ISSUE THREAD

**Issue by 6D65** [dtolnay/syn#276]
Hi,

It fails to compile in stable Rust, with a simple example.
Should it work in stable Rust? Maybe I'm missing some features in Cargo.toml?

Thanks,

Cargo.toml
```toml
[dependencies.syn]
version = "0.11"
default-features = false
features = ["full", "printing", "parsing"]
```

Error
```sh
error[E0425]: cannot find function `parse_file` in module `syn`
  --> src\main.rs:13:20
   |
13 |     let ast = syn::parse_file(&src).expect("Unable to parse file");
   |                    ^^^^^^^^^^ did you mean `parse_item`?

```

Sample program:
```rust
extern crate syn;

use std::fs::File;
use std::io::{self, Read};

fn main() {
    let mut src = String::new();
    let mut file = File::open("sample.rs").expect("Unable to open source file");
    file.read_to_string(&mut src).expect(
        "Unable to read input file",
    );

    let ast = syn::parse_file(&src).expect("Unable to parse file");
    println!("{:#?}", ast);
}
```

```ps1
PS > rustc --version
rustc 1.22.1 (05e2e1c41 2017-11-22)
```
