### ISSUE TITLE
Syn can't parse `#[foo(bar = true)]` anymore

### ISSUE THREAD

**Issue by Eijebong** [dtolnay/syn#346]
Cargo.toml
```toml
[package]                                              
name = "foo"                                       
version = "0.1.0"                                       
                                                       
[dependencies]                                         
syn = { version = "0.12", features = ["extra-traits"] }
proc-macro2 = "0.2"                                    

```

src/main.rs
```rust
extern crate syn;                                                                                                                
extern crate proc_macro2;                                                                                                        
                                                                                                                                 
use syn::synom::Parser;                                                                                                          
use std::str::FromStr;                                                                                                           
                                                                                                                                 
fn main() {                                                                                                                      
    let ast = syn::Attribute::parse_outer.parse2(proc_macro2::TokenStream::from_str("#[foo(bar = true)]").unwrap()).unwrap();    
    println!("{:?}", ast.interpret_meta());                                                                                      
    let ast = syn::Attribute::parse_outer.parse2(proc_macro2::TokenStream::from_str("#[foo(bar = \"true\")]").unwrap()).unwrap();
    println!("{:?}", ast.interpret_meta());                                                                                      
    let ast = syn::Attribute::parse_outer.parse2(proc_macro2::TokenStream::from_str("#[foo(bar = 2)]").unwrap()).unwrap();       
    println!("{:?}", ast.interpret_meta());                                                                                      
}                                                                                                                                
```

Output
```
None
Some(List(MetaList { ident: Ident { term: Term("foo"), span: Span }, paren_token: Paren, nested: [(Meta(NameValue(MetaNameValue { ident: Ident { term: Term("bar"), span: Span }, eq_token: Eq, lit: Str(LitStr { token: Literal("\"true\""), span: Span }) })), None)] }))
Some(List(MetaList { ident: Ident { term: Term("foo"), span: Span }, paren_token: Paren, nested: [(Meta(NameValue(MetaNameValue { ident: Ident { term: Term("bar"), span: Span }, eq_token: Eq, lit: Int(LitInt { token: Literal("2"), span: Span }) })), None)] }))
```

This is causing some problems for this [darling test](https://github.com/TedDriggs/darling/blob/3787d08c8ce5dd00cab2ff762d70ef50a933f9e3/tests/accrue_errors.rs#L34)
