### ISSUE TITLE
`0 < -1` becomes `0 <- 1` inside macro_rules when proc-macro2 has feature nightly

### ISSUE THREAD

**Issue by CodeSandwich** [dtolnay/syn#425]
When proc-macro2 has set feature `nightly`, parsing inside `macro_rules` becomes buggy. `0 < -1`, which is comparison gets glued into `0 <- 1`, which is assignment.

## Reproduction
Tested using rustc 1.27.0-nightly (acd3871 2018-05-10).
### Macro `Cargo.toml`
```toml
[package]
name = "macros"
version = "0.1.0"
[lib]
proc-macro = true
[dependencies]
syn = { version = "0.13.10", features = ["full"] }
quote = "0.5.2"
proc-macro2 = { version = "0.3.8" }
```
### Macro `lib.rs`
```rust
#![feature(proc_macro)]
extern crate proc_macro;
extern crate proc_macro2;
extern crate syn;
extern crate quote;
use proc_macro::TokenStream;
use quote::ToTokens;
#[proc_macro_attribute]
pub fn nothing(_: TokenStream, token_stream: TokenStream) -> TokenStream {
    let tokens = syn::parse::<syn::Item>(token_stream)
        .unwrap()
        .into_tokens()
        .into();
    println!("{}", tokens);
    tokens
}
```
### Macro user `lib.rs`
```rust
#![feature(proc_macro)]
#![allow(unused_macros)]
extern crate macros;
use macros::nothing;
#[nothing]
macro_rules! mr {
    () => { 0 < -1 }
}
```
### Output
```rust
macro_rules ! mr ( (  ) => { 0 < - 1 } ) ;
```
### Macro `Cargo.toml` modification
```toml
proc-macro2 = { version = "0.3.8", features = ["nightly"] }
```
### Output after modification
```rust
macro_rules ! mr ( (  ) => { 0 <- 1 } ) ;
```
