### ISSUE TITLE
Formal function attributes is still unsupported?

### ISSUE THREAD

**Issue by Hexilee** [dtolnay/syn#685]
As this [example repo](https://github.com/Hexilee/params-attribute-example/blob/master/proc-macro-tests/rename_params.rs)

This is the example proc-macro:

```rust
#![feature(proc_macro_diagnostic)]

extern crate proc_macro;
use proc_macro::{Diagnostic, Level, TokenStream};
use quote::quote;
use syn::{
    parse::{Parse, Parser},
    FnArg, ItemFn, Pat,
};

#[proc_macro_attribute]
pub fn rename_params(_args: TokenStream, input: TokenStream) -> TokenStream {
    let func = <ItemFn as Parse>::parse.parse(input).unwrap();
    for arg in func.sig.inputs.iter() {
        if let FnArg::Typed(pat) = arg {
            if let Pat::Ident(name) = pat.pat.as_ref() {
                Diagnostic::new(
                    Level::Note,
                    format!(
                        "arg({}), PatType.attrs.len = {}, PatIdent.attrs.len = {}",
                        name.ident,
                        pat.attrs.len(),
                        name.attrs.len()
                    ),
                )
                .emit();
            }
        }
    }
    quote!(#func).into()
}

```

This is the test:

```rust
#![feature(param_attrs)]
use params_attribute_example::rename_params;

#[rename_params]
fn hello(a: i32, #[val] b: i32) {}
```

run `cargo expand`:

```rust
note: arg(a), PatType.attrs.len = 0, PatIdent.attrs.len = 0
note: arg(b), PatType.attrs.len = 0, PatIdent.attrs.len = 0

fn hello(a: i32, b: i32) {}
```

I cannot get the attributes of parameter. How can I get it?

`Cargo.toml`:

```toml
[dependencies]
proc-macro2-next = { version = "1.0.0-rc1" }
quote-next = { version = "1.0.0-rc1" }
syn-next = { version = "1.0.0-rc1", features = ["full", "visit-mut"] }

[lib]
proc-macro = true

[patch.crates-io]
syn-next = { git = "https://github.com/dtolnay/syn", branch = "master"}
proc-macro2-next = { git = "https://github.com/alexcrichton/proc-macro2", branch = "next" }
quote-next = { git = "https://github.com/dtolnay/quote" }
```

toolchain: `nightly-x86_64-apple-darwin(8a58268b5 2019-07-31)`
